### ISSUE TITLE
Use casbin as the permission backend

### ISSUE THREAD

**Issue by hsluoyz** [xyproto/permissions2#13]
Hi, there is a project called [casbin](https://github.com/hsluoyz/casbin). It is an authorization library that supports models like MAC, RBAC, ABAC. Maybe it can assist your need in the perm management.

**Comment by xyproto** [comment]
Thanks for the tip, I will look into it.

**Comment by xyproto** [comment]
It looks to me like casbin and permissions2 have different goals and fullfills different purposes.

`permissions2` tries to keep things really simple and configuration-less by default, while offering the means to implement more fine-grained security, for those that are interested in that.

casbin has a lot of nice features readily implemented and is probably a better fit for developers that want those exact features and methods of configuring access control.

Thanks for the tip about casbin. Cheers!
