### ISSUE TITLE
Change "username" to "useridentity" or "userid"

### ISSUE THREAD

**Issue by siredwin** [xyproto/permissions2#15]
Hello again, 

I have managed to incorporate permissions2 into my project and I think  that small change can make a big difference. Permissions2 is by far the most flexible user auth package in go.
By default "username" seems to be a unique field as I quess was the original intention of the project. But to make it really unique I have found myself using email or uuid for username.
If it was "useridentity" or "userid", then I could easily use email or uuid or anything unique without having to worry about code readability later.  I would also still have username available for an actual username or useralias.

**Comment by xyproto** [comment]
Thank you for the suggestion. I will consider either:

* Renaming `username` to `userid` everywhere, and adding a `username` field for the username, which is a breaking change, but makes sense.
or
* Keeping all the existing functions and adding similar functions where it is possible to manage users with `userid` as the ID and `username` as an extra field.

I will try the second method first, but if it turns out to be too ugly I will consider making a breaking change and update the major version number.

**Comment by xyproto** [comment]
After having looked at this, I think the cost of breaking backwards compatibility is too high.

Is just using `username` and thinking of it as `userid` a possibility? Or alternatively wrapping the `permissions2` functions that mentions `username` in local functions that has more intuitive names (and perhaps does additional things, like checking that the userID is a valid e-mail address, in the same go?).

**Comment by siredwin** [comment]
Thinking of a `username` as a `userid` works. You would have to force users to create unique ones and it wouldn't be long before you start seeing names like `bob1234` , or find a way to recommend  new usernames to users.   
In my experience:   
- users do not remember recommend names 
- would prefer to use their own names 
- they also would rather login using email
- recommended or unique names forces users to always forget them, leading to resets,  and discouragement.  

Using username alone does not really work like most  modern logins. I come from a background in PHP and Python web developments.
The changes i made that work for me are:
- I made users be searchable my `emails`
- `username` is an `auto-generated uuid` linked to `email`
- `email` is a `unique` field
- what users enter as `name` is `name_alias`

**Comment by siredwin** [comment]
But since you have implemented `HasEmail`.  `Emails` can now work as `unique` field and that would satisfy registering users using unique fields.  
This can be a satisfactory answer,  as the rest can be implemented easily in 
[Setting and getting properties for users](https://github.com/xyproto/permissions2#setting-and-getting-properties-for-users).

**Comment by xyproto** [comment]
Thanks for the observations about users and email as the best "username", I'll keep that in mind.

I also added `HasEmail` to the `pstore` package.
