### ISSUE TITLE
Encrypted connection to Redis

### ISSUE THREAD

**Issue by pierrefar** [xyproto/permissions2#17]
Hello

I'm looking at connecting to Redis with the data encrypted in transit. One public example would be using AWS Elasticache as the Redis backend with the feature enabled as [described here](https://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/in-transit-encryption.html).

It doesn't appear to be possible to configure this kind of encryption for permissions2. Is that correct or did I miss something? If yes, can you please consider adding support for this functionality? If not, can we have a code example? 

Speaking of which, the code examples are great and much appreciated!

Thanks,
Pierre

**Comment by xyproto** [comment]
Hi Perre,

Thank you for the suggestion. I looked over the article you linked to, but could not find anything I can do to make permissions2 better adjusted for this.

I might be wrong, but to me it looks like "Amazon ElastiCache for Redis In-Transit Encryption" operates on a layer above and outside of the redis server/clients that communicate, and that the redis-related software should just communicate as usual.

I'm glad the code examples were appreciated. I always prefer code examples myself, when testing out a new Go package.

Best regards,
Alexander
