### ISSUE TITLE
memory persistent or golang key/val alternative to redis?

### ISSUE THREAD

**Issue by cocodrino** [xyproto/permissions2#6]
Hi, I'm interested in use permissions but I'd like avoid install redis for small projects, I know than redis is great and I'm currently using it in medium/big projects but for small ones seems a bit unnecessary, would be possible use maybe a key/value golang storage and avoid need install more tools?...or maybe a memory persistent...

thanks

**Comment by xyproto** [comment]
Hi,

permissionbolt might be what you are looking for?

From the README:
> For Bolt database support (no database host needed, uses a file), look into [permissionbolt](https://github.com/xyproto/permissionbolt).
