### ISSUE TITLE
How to change existing user's password ?

### ISSUE THREAD

**Issue by Georges760** [xyproto/permissions2#7]
There is no function in UserState permitting to hange a user password (update the password hash).

Would it be possible to have one ?

**Comment by xyproto** [comment]
Hi,

I agree that such a function would be nice to have. I will consider implementing one.

In the mean time, the following works, for changing the password:

    // Change the password for user "bob" to "hunter2"
    username := "bob"
    password := "hunter2"
    passwordHash := userstate.HashPassword(username, password)
    userstate.Users().Set(username, "password", passwordHash)

Best regards,
Alexander F Rødseth

**Comment by Georges760** [comment]
Great,
this method works great, so I can use it for now. When I will be done, I will find some time to do the "func (state *UserState) ChangePassword(username, password string) error" function for you.

**Comment by xyproto** [comment]
Added `SetPassword`.
