### ISSUE TITLE
Make cookie secret public variable

### ISSUE THREAD

**Issue by sokolovstas** [xyproto/permissions2#8]
We find out that every time when we restart server we have different cookie secret. We don't use rand package and don't seed it, that may be doing one of another package, but we don't have control over that.

**Comment by sokolovstas** [comment]
I have added pull request with getter/setter #9

**Comment by xyproto** [comment]
Thanks for reporting! Will look into the issue.

**Comment by xyproto** [comment]
Merged #9, thanks for contributing.

**Comment by sokolovstas** [comment]
Thank you!
